### ISSUE TITLE
cdc-sink pglogical

### ISSUE THREAD

**Issue by malligit** [cockroachdb/cdc-sink#100]
I am trying to start the cdc-sink for replicating the data from postgres db to crdb. i am using the below command

cdc-sink pglogical --publicationName <mc_publication> --sourceConn <source connection string>/ --targetConn <target connection string> --targetDB <application_db>

i am getting the below error

error="no target db was configured"
i have the db configured in the target cluster.

Let me know what i am missing

**Comment by bobvawter** [comment]
That check takes the value parsed in the CLI command here:
https://github.com/cockroachdb/cdc-sink/blob/master/internal/cmd/pglogical/pglogical.go#L45

And immediately checks the value in `NewConn()` here:
https://github.com/cockroachdb/cdc-sink/blob/master/internal/source/pglogical/conn.go#L110

Are you using any shell substitutions or environment variables to launch `cdc-sink`?

**Comment by bobvawter** [comment]
There is no backfilling at present; that's on the to-do list as #95.  In the interim, you can run `pg_dump` after creating the replication slot.  Import the bulk data into CRDB and then start `cdc-sink`.
