### ISSUE TITLE
Rename the Project to Brooklyn Bridge

### ISSUE THREAD

**Issue by BramGruneir** [cockroachdb/cdc-sink#104]
The original goal of cdc-sink was just to take in a CockroachDB cdc feed and upsert it into another CockroachDB.  

As this project has evolved to being able to take in other types of feeds, I feel it's time that it's name be changed to something less exacting.

I think Brooklyn Bridge is a good and catchy name for it.  Cockroach Labs is located (primarily) in NYC and this tool acts as a bridge to help get data into the db.

**Comment by bobvawter** [comment]
I have no particular preference for the naming of the project, but we will need to coordinate with the dev-inf group to redo the DockerHub repo setup.

**Comment by bobvawter** [comment]
I have no particular preference for the naming of the project, but we will need to coordinate with the dev-inf group to redo the DockerHub repo setup.
