### ISSUE TITLE
Sporadic unexpected EOF messages

### ISSUE THREAD

**Issue by sravotto** [cockroachdb/cdc-sink#111]
Seeing sporadic unexpected EOF messages while running a tpcc workload on postgres and replicating it to crdb

```
WARNING[Apr  6 19:12:01] error while flushing mutations; will retry    
error="UPSERT INTO \"benchbase\".\"public\".\"history\"
(\n\"h_c_id\",\"h_c_d_id\",\"h_c_w_id\",\"h_d_id\",\"h_w_id\",\"h_date\",\"h_amount\",\"h_data\"\n) 
VALUES\n($1::INT8,$2::INT8,$3::INT8,$4::INT8,$5::INT8,$6::TIMESTAMP,$7::DECIMAL(6,2),$8::VARCHAR(24)): unexpected EOF"
```

**Comment by bobvawter** [comment]
I would expect to see that message if network connections from cdc-sink to the cluster's SQL loadbalancer are being interrupted.  Does the replication process continue past that point?

**Comment by BramGruneir** [comment]
closing as this is quite old
