### ISSUE TITLE
Use flag groups

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cdc-sink#163]
New feature in flags library from https://github.com/cockroachdb/cdc-sink/pull/160 allows groups of flags to be required as a group.  This would be useful for some of the TLS flags, where we need the key and certificate as pairs.

**Comment by BramGruneir** [comment]
@bobvawter , didn't you just complete work that more or less does this?

**Comment by bobvawter** [comment]
It's handled by the various `Preflgiht()` methods in the configuration types.
