### ISSUE TITLE
Support https endpoint

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cdc-sink#18]
Did the following on the source:
```
CREATE CHANGEFEED FOR TABLE me INTO 'experimental-https://172.31.2.194:26258/me.sql' WITH resolved, updated;
```
The log from the *source* machine showed:
```
error: retryable changefeed error: retryable http error: Put https://172.31.2.194:26258/me.sql/2020-04-19/202004191704475286656650000000001-bcfd19dba28ea94a-3-5017-00000000-me-1.ndjson: http: server gave HTTP response to HTTPS client
```

**Comment by bobvawter** [comment]
Work in #73 will make it easier to add a TLS configuration to the http server.  Can also dig up code to have the cdc-sink server generate a self-signed certificate for testing purposes.

**Comment by bobvawter** [comment]
Needed to implement this in #73 to support v21.2's `webhook-https://` scheme.
