### ISSUE TITLE
cdc: Out of Memory /w 10warehouse TPCC sink

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cdc-sink#22]
5, "ol_number": 8, "ol_o_id": 1236, "ol_quantity": 5, "ol_supply_w_id": 4, "ol_w_id": 4}, "key": [4, 7, 1236, 8], "updated": "1587320776859132078.0000000000"}
2020/04/19 23:39:56 lineRaw: {"after": {"c_balance": -10.00, "c_city": "wsmd68P2bElAgr", "c_credit": "GC", "c_credit_lim": 50000.00, "c_d_id": 10, "c_data": "np8ueWNXJpBB0ObpVWo1BahdejZrKB2O3Hzk13xWSP8P9fwb2ZjtZAs3NbYdihFxFime6B6Adnt5jrXvRR7OGYhlpdljbDvShaRF4E9zNHsJ7ZvyiJ3n2X1f4fJoMgn5buTDyUmQupcYMoPylHqYo89SqHqQ4HFVNpmnIWHyIowzQN2r4uSQJ8PYVLLLZk9Epp6cNEnaVrN3JXcrBCOuRRSlC0zvh9lctkhRvAvE5H6TtiDNPEJrcjAUOegvQ1Ol7SuF7jPf275wNDlEbdC58hrunlPfhoY1dORoIgb0VnxqkqbEWTXujHUOvCRfqCdVyc8gRGMfAd4nWB1rXYANQ0fa6ZQJJI2uTeFFazaVwxnN13XunKGV6AwCKxhJQVgXWaljKLJ7r175FAuGYFLyx", "c_delivery_cnt": 0, "c_discount": 0.3930, "c_first": "raPxxELo5B1fcW", "c_id": 251, "c_last": "ABLEESEBAR", "c_middle": "OE", "c_payment_cnt": 1, "c_phone": "4732942322014469", "c_since": "2006-01-02T15:04:05", "c_state": "VW", "c_street_1": "8RsaCXoEzmssaF9", "c_street_2": "m9cdLXe0YhgLRr", "c_w_id": 7, "c_ytd_payment": 10.00, "c_zip": "082911111"}, "key": [7, 10, 251], "updated": "1587320776788760053.0000000000"}
**fatal error: runtime: out of memory**

runtime stack:
runtime.throw(0x798d32, 0x16)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/panic.go:617 +0x72
runtime.sysMap(0xc058000000, 0x4000000, 0xa68378)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/mem_linux.go:170 +0xc7
runtime.(*mheap).sysAlloc(0xa500e0, 0x211c000, 0xa500f0, 0x108e)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/malloc.go:633 +0x1cd
runtime.(*mheap).grow(0xa500e0, 0x108e, 0x0)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/mheap.go:1222 +0x42
runtime.(*mheap).allocSpanLocked(0xa500e0, 0x108e, 0xa68388, 0x7fb165258fd0)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/mheap.go:1150 +0x37f
runtime.(*mheap).alloc_m(0xa500e0, 0x108e, 0x7fb166460100, 0xa500f0)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/mheap.go:977 +0xc2
runtime.(*mheap).alloc.func1()
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/mheap.go:1048 +0x4c
runtime.(*mheap).alloc(0xa500e0, 0x108e, 0xc000010100, 0x7fb1664659e0)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/mheap.go:1047 +0x8a
runtime.largeAlloc(0x211c000, 0x7fb166610001, 0x7fb1664659e0)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/malloc.go:1055 +0x99
runtime.mallocgc.func1()
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/malloc.go:950 +0x46
runtime.systemstack(0x0)
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/asm_amd64.s:351 +0x66
runtime.mstart()
        /usr/local/Cellar/go/1.12.6/libexec/src/runtime/proc.go:1153

**Comment by robert-s-lee** [comment]
@glennfawcett added instruction on `add-tpcc-example` branch.  can you check against your test steps

**Comment by BramGruneir** [comment]
This is quite old.  Closing.
