### ISSUE TITLE
Update documentation to include manually creating a temp db

### ISSUE THREAD

**Issue by mikeczabator** [cockroachdb/cdc-sink#248]
The instructions should mention that a temp db needs to be manually created on the destination cluster, for ex: `CREATE DATABASE _cdc_sink;`.

**Comment by BramGruneir** [comment]
I think we have this already:
See step 3 here:   https://github.com/cockroachdb/cdc-sink/wiki/C2C#instructions

There is a larger project we need to start working on to re-work the wiki a bit.  But I'm going to close this out.
