### ISSUE TITLE
Supply Sink Lag Time metric

### ISSUE THREAD

**Issue by glennfawcett** [cockroachdb/cdc-sink#390]
The `logical_last_commit_seconds` is provided but to compute lag the current time must be gathered and the difference computed.   This can be done for a point-in-time with Grafana, but requires an extra call to CRDB to extract the current_timestamp.  Also, this value can't be stored in Grafana to show offset history over time.  I am going to deploy visus to gather the following from the target database:

```sql
SELECT extract(epoch from current_timestamp) - min(source_nanos/1000000000)::float as sink_lag_seconds
FROM resolved_timestamps
WHERE target_applied_at is NULL;
```

If the `sink_lag_seconds` was a supplied logical metric it would be more efficient and less cumbersome to display the sink lag time.

**Comment by bobvawter** [comment]
Isn't that `logical_commit_latency_seconds` ?

> the current time minus the original time of the most recently applied commit from the source database

**Comment by glennfawcett** [comment]
sorry, a mistype ... `logical_commit_latency_seconds` is the metric supplied calculate to help compute lag.  It would be better to just simply have the time difference like mentioned above.
