### ISSUE TITLE
pglogical.lsnStamp is not well-ordered

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cdc-sink#459]
The order in which we receive `BeginMessage` doesn't necessarily line up with their starting LSNs.  We need to investigate if the XID (with wraparound) is a better way to make `lsnStamp` well-ordered. There are additional LSN values associated with `CommitMessage` and should be researched. It would also be possible to add an extra method to `logical.Events` to allow the transaction stamp to be swizzled, but this may require replacing the use of stamps with handles to stamps in the logical package. See discussion in PR #458.

**Comment by BramGruneir** [comment]
@sravotto , can you take a look into this?

**Comment by bobvawter** [comment]
No need, I have a PR about to ship that will resolve this.
