### ISSUE TITLE
Data-loss during CRDB-2-CRDB replication

### ISSUE THREAD

**Issue by sjuls** [cockroachdb/cdc-sink#476]
We are attempting to use cdc-sink to split off databases from clusters into new isolated clusters. To validate our process we've been testing using the `movr` workload provided by the cockroach cli.

The problem we're facing is that we are experiencing data-loss on the `endRide` updates of the workload while running the tests in our staging environment. This data-loss has been consistent across 4 separate trial runs, though we have so far been unable to reproduce this issue locally via scripting the process. The changes are present on the cdc-sink staging table seem to not be applied to the target database.

We obviously cannot proceed with moving production workloads until we are guaranteed not to drop any changes, so we're hoping for some assistance to identify and resolve the issue.

## Process:

1. Init movr workload `cockroach workload init movr --drop --num-histories=100000 --num-promo-codes=100000 --num-rides=50000 --num-users=5000 --num-vehicles=1500 '<url>'`
2. Start movr workload continuously
3. Start cdc-sink `cdc-sink start --foreignKeys --disableAuthentication --bytesInFlight=128000000 --tlsSelfSigned --retireOffset '24h' --stagingSchema 'movr.cdcsink' --targetConn '<url>'`
4. `SELECT cluster_logical_timestamp();` to get a timestamp T
5. BACKUP movr AS OF SYSTEM T from source
6. RESTORE movr onto target
7. `CREATE CHANGEFEED FOR TABLE movr.users,movr.vehicles,movr.rides,movr.vehicle_location_histories,movr.promo_codes,movr.user_promo_codes
  INTO 'webhook-https://<cdc-sink-hostnamel>:443/movr/public?insecure_tls_skip_verify=true'
  WITH updated, resolved='1s', cursor='1694675849704637023.0000000000', min_checkpoint_frequency='1s',
       webhook_sink_config='{"Flush":{"Messages":1000,"Frequency":"1s"}}';`
       
Missing data:
![Screenshot 2023-09-14 at 10 33 19](https://github.com/cockroachdb/cdc-sink/assets/29860500/6a26c883-cb2a-4852-b51d-d39254c3cb80)

Staging contains the changes:
![Screenshot 2023-09-14 at 10 38 50](https://github.com/cockroachdb/cdc-sink/assets/29860500/8a3b40ec-cba5-4731-bccf-9c7190fc7c15)

cdc-sink sha: bfb21afa375a95122c2512cad8ead6c68163471f
cockroachdb: v23.1.8

**Comment by bobvawter** [comment]
Can you make a backup of that database available via your CEA?  I'd like to restore it to be able to poke around at the `_cdc_sink.resolved_timestamp` entries that bracket the missed update as well as the MVCC timestamps of the missed update and the resolved timestamps that should have selected that value.

I wouldn't expect the `end_time` column to be special in any way, but do you see examples of missing data elsewhere in the `movr` dataset?  If it's only the `end_time` updates that are missing, then it would imply there's something specific about the data access patterns and/or timing that I can focus on.

**Comment by sjuls** [comment]
Sure, backup attached [movr.tar.gz](https://github.com/cockroachdb/cdc-sink/files/12612430/movr.tar.gz). 

Both the `end_time` and `end_address` columns are  missing data, which matches the [endRide](https://github.com/cockroachdb/cockroach/blob/d05cdeb541e866f30382b48a46599521734e8e2c/pkg/workload/movr/workload.go#L199) action of the movr workload. We haven't seen missing data from other actions.

**Comment by bobvawter** [comment]
That backup seems to be missing an sst file: `movr/2023/09/14-185201.99/data/899963691136843778.sst`

**Comment by sjuls** [comment]
You're right, sorry about that - this one seems to work on my end: [movr2.tar.gz](https://github.com/cockroachdb/cdc-sink/files/12612781/movr2.tar.gz).

**Comment by bobvawter** [comment]
That one restores, can I also get the `_cdc_sink` staging database as well?

**Comment by bobvawter** [comment]
Please disregard previous, I see the `_cdc_sink` tables are included.  Let me take a look and I'll get back to you.

**Comment by bobvawter** [comment]
It looks like there was a `1m10s` break in resolved-timestamp delivery just prior to the missed update.  That would be consistent with the loop-retry delay of `10s` plus the resolver lease-expiration time of `1m`.

Were there any errors in the cdc-sink log around the missed-update time?  Is cdc-sink running on an orchestration platform that could have rescheduled a pod, network blip, etc?  If the missed update is due to an operational/environment issue, that might explain why it's not reproducing locally.  I'm wondering if there's an (unreliable) error path that's not covered by the chaos fuzzing leading to the resolved timestamp being marked as complete, but without the mutations being applied.

```
root@localhost:26257/movr> select nanos, key, convert_from(mut, 'utf8')  from cdcsink.movr_public_rides where key like '%3d309f23%' order by nanos;
         nanos        |                       key                       |                                                                                                                                                                                 convert_from
----------------------+-------------------------------------------------+--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  1694676380841627173 | ["rome","3d309f23-3244-4f82-8c26-e70d115e4b40"] | {"city":"rome","end_address":null,"end_time":null,"id":"3d309f23-3244-4f82-8c26-e70d115e4b40","revenue":76.00,"rider_id":"fc91d14e-3bcd-4800-8000-000000001345","start_address":"22026 Rhodes Ridges Suite 80","start_time":"2023-09-14T07:26:20.841619","vehicle_city":"rome","vehicle_id":"e76c8b43-9581-4800-8000-00000000054c"}
  1694676415474805516 | ["rome","3d309f23-3244-4f82-8c26-e70d115e4b40"] | {"city":"rome","end_address":"30348 Elizabeth Park","end_time":"2023-09-14T07:26:55.474799","id":"3d309f23-3244-4f82-8c26-e70d115e4b40","revenue":76.00,"rider_id":"fc91d14e-3bcd-4800-8000-000000001345","start_address":"22026 Rhodes Ridges Suite 80","start_time":"2023-09-14T07:26:20.841619","vehicle_city":"rome","vehicle_id":"e76c8b43-9581-4800-8000-00000000054c"}
(2 rows)


Time: 2ms total (execution 1ms / network 0ms)

root@localhost:26257/movr> SELECT *,                                                                                                                                                                                        target_applied_at - source_time AS lag,                                                                                                                                                                              ((source_nanos - 1694676415474805516) / 1e9)::INTERVAL AS trouble_delta                                                                                                                                         FROM (                                                                                                                                                                                                                       SELECT source_nanos,                                                                                                                                                                                                        to_timestamp((source_nanos / 1e9)::FLOAT8) AS source_time,                                                                                                                                                           target_applied_at                                                                                                                                                                                               FROM cdcsink.resolved_timestamps                                                                                                                                                                                    WHERE source_nanos >= 1694676356846241840                                                                                                                                                                         ORDER BY source_nanos                                                                                                                                                                                                   LIMIT 16                                                                                                                                                                                                         );
     source_nanos     |          source_time          |     target_applied_at      |       lag       |  trouble_delta
----------------------+-------------------------------+----------------------------+-----------------+-------------------
  1694676356846241840 | 2023-09-14 07:25:56.846242+00 | 2023-09-14 07:26:01.003632 | 00:00:04.15739  | -00:00:58.628564
  1694676357857794034 | 2023-09-14 07:25:57.857794+00 | 2023-09-14 07:26:02.012018 | 00:00:04.154224 | -00:00:57.617011
  1694676358868781444 | 2023-09-14 07:25:58.868781+00 | 2023-09-14 07:26:02.989804 | 00:00:04.121023 | -00:00:56.606024
  1694676359880534749 | 2023-09-14 07:25:59.880535+00 | 2023-09-14 07:26:04.020587 | 00:00:04.140052 | -00:00:55.594271
  1694676430065508014 | 2023-09-14 07:27:10.065508+00 | 2023-09-14 07:27:14.876755 | 00:00:04.811247 | 00:00:14.590702
  1694676432248692353 | 2023-09-14 07:27:12.248692+00 | 2023-09-14 07:27:25.149004 | 00:00:12.900312 | 00:00:16.773887
  1694676433258609529 | 2023-09-14 07:27:13.258609+00 | 2023-09-14 07:27:25.224201 | 00:00:11.965592 | 00:00:17.783804
  1694676434338383157 | 2023-09-14 07:27:14.338383+00 | 2023-09-14 07:27:25.288067 | 00:00:10.949684 | 00:00:18.863578
  1694676435338577867 | 2023-09-14 07:27:15.338578+00 | 2023-09-14 07:27:25.343363 | 00:00:10.004785 | 00:00:19.863772
  1694676437191749774 | 2023-09-14 07:27:17.19175+00  | 2023-09-14 07:27:25.403154 | 00:00:08.211404 | 00:00:21.716944
  1694676439229103419 | 2023-09-14 07:27:19.229103+00 | 2023-09-14 07:27:25.462205 | 00:00:06.233102 | 00:00:23.754298
  1694676440944943382 | 2023-09-14 07:27:20.944943+00 | 2023-09-14 07:27:25.539301 | 00:00:04.594358 | 00:00:25.470138
  1694676442360519607 | 2023-09-14 07:27:22.36052+00  | 2023-09-14 07:27:26.769976 | 00:00:04.409456 | 00:00:26.885714
  1694676444325015800 | 2023-09-14 07:27:24.325016+00 | 2023-09-14 07:27:28.452179 | 00:00:04.127163 | 00:00:28.85021
  1694676446357507072 | 2023-09-14 07:27:26.357507+00 | 2023-09-14 07:27:30.428875 | 00:00:04.071368 | 00:00:30.882702
  1694676448196790769 | 2023-09-14 07:27:28.196791+00 | 2023-09-14 07:27:32.431045 | 00:00:04.234254 | 00:00:32.721985
(16 rows)

```

**Comment by sjuls** [comment]
Hi @bobvawter,

There is actually one single error message at 07:27:15 that I somehow missed. I've searched through the logs and this error message does not appear on the previous 3 trials which also had similar data-loss, so it might be a red herring.

For context the changefeed is started at 07:27:12.565578.

The cdc-sink process is running as a pod on kubernetes, but no pod restarts were observed during the trial run. Is cdc-sink not expected to be resilient against restart and network disruptions?

```
time="Sep 14 07:27:15" level=error msg="error in replication loop changefeed-movr.public; retrying in 10s" detail="consistent point going backwards: {\"c\":\"1694676359880534749.0000000000\",\"i\":2,\"p\":\"1694676430065508014.0000000000\",\"otbl\":[],\"ots\":\"0.0000000000\"} vs {\"c\":\"1694676430065508014.0000000000\",\"p\":\"0.0000000000\",\"otbl\":[],\"ots\":\"0.0000000000\"}\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*loop).setConsistentPoint\n\t/tmp/compile/internal/source/logical/loop.go:136\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*serialEvents).OnCommit\n\t/tmp/compile/internal/source/logical/serial_events.go:91\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*orderedEvents).OnCommit\n\t/tmp/compile/internal/source/logical/ordered_events.go:90\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*metricsEvents).OnCommit\n\t/tmp/compile/internal/source/logical/metrics_events.go:79\ngithub.com/cockroachdb/cdc-sink/internal/source/cdc.(*resolver).process.func1\n\t/tmp/compile/internal/source/cdc/resolver.go:386\ngithub.com/cockroachdb/cdc-sink/internal/source/cdc.(*resolver).process.func2\n\t/tmp/compile/internal/source/cdc/resolver.go:432\ngithub.com/cockroachdb/cdc-sink/internal/staging/stage.(*factory).SelectMany\n\t/tmp/compile/internal/staging/stage/factory.go:272\ngithub.com/cockroachdb/cdc-sink/internal/source/cdc.(*resolver).process\n\t/tmp/compile/internal/source/cdc/resolver.go:407\ngithub.com/cockroachdb/cdc-sink/internal/source/cdc.(*resolver).Process\n\t/tmp/compile/internal/source/cdc/resolver.go:280\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*loop).runOnceUsing.func2\n\t/tmp/compile/internal/source/logical/loop.go:390\ngithub.com/cockroachdb/cdc-sink/internal/util/stopper.(*Context).Go.func1\n\t/tmp/compile/internal/util/stopper/stopper.go:152\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\norderedEvents OnCommit\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*orderedEvents).OnCommit\n\t/tmp/compile/internal/source/logical/ordered_events.go:90\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*metricsEvents).OnCommit\n\t/tmp/compile/internal/source/logical/metrics_events.go:79\ngithub.com/cockroachdb/cdc-sink/internal/source/cdc.(*resolver).process.func1\n\t/tmp/compile/internal/source/cdc/resolver.go:386\ngithub.com/cockroachdb/cdc-sink/internal/source/cdc.(*resolver).process.func2\n\t/tmp/compile/internal/source/cdc/resolver.go:432\ngithub.com/cockroachdb/cdc-sink/internal/staging/stage.(*factory).SelectMany\n\t/tmp/compile/internal/staging/stage/factory.go:272\ngithub.com/cockroachdb/cdc-sink/internal/source/cdc.(*resolver).process\n\t/tmp/compile/internal/source/cdc/resolver.go:407\ngithub.com/cockroachdb/cdc-sink/internal/source/cdc.(*resolver).Process\n\t/tmp/compile/internal/source/cdc/resolver.go:280\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*loop).runOnceUsing.func2\n\t/tmp/compile/internal/source/logical/loop.go:390\ngithub.com/cockroachdb/cdc-sink/internal/util/stopper.(*Context).Go.func1\n\t/tmp/compile/internal/util/stopper/stopper.go:152\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nerror while applying replication messages\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*loop).runOnceUsing.func2\n\t/tmp/compile/internal/source/logical/loop.go:396\ngithub.com/cockroachdb/cdc-sink/internal/util/stopper.(*Context).Go.func1\n\t/tmp/compile/internal/util/stopper/stopper.go:152\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598\nloop changefeed-movr.public\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*loop).runOnceUsing\n\t/tmp/compile/internal/source/logical/loop.go:474\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*loop).runOnce\n\t/tmp/compile/internal/source/logical/loop.go:325\ngithub.com/cockroachdb/cdc-sink/internal/source/logical.(*loop).run\n\t/tmp/compile/internal/source/logical/loop.go:251\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1598" error="loop changefeed-movr.public: error while applying replication messages: orderedEvents OnCommit: consistent point going backwards: {\"c\":\"1694676359880534749.0000000000\",\"i\":2,\"p\":\"1694676430065508014.0000000000\",\"otbl\":[],\"ots\":\"0.0000000000\"} vs {\"c\":\"1694676430065508014.0000000000\",\"p\":\"0.0000000000\",\"otbl\":[],\"ots\":\"0.0000000000\"}"
```

**Comment by bobvawter** [comment]
cdc-sink is intended to be deployed as a (replicated) k8s service, with the attendant operational quirks therein.  So this ought to work, but there's a sequence of events that results in missed updates.  I have roped another engineer in to build this movr+k8s case on Monday.

**Comment by glennfawcett** [comment]
I have built out a non-local multi-cluster test environment with `movr` and cdc-sink.  I followed your test process and see no issues.  I upped the stress on the system and tested over last weekend, but still no reproduction.  

I would say this has something to do with your test environment and/or scripting.

**Comment by sjuls** [comment]
Hi @glennfawcett ,

Appreciate your efforts trying to reproduce. I have so far also been unable to reproduce it locally as stated in the issue description, so it is definitely under very special circumstances that these changes are dropped.

Can you elaborate on how you suspect our environment and/or scripting is leading to a loss of changes in the middle of a stream of changes, with changes both before and after being successfully applied?

**Comment by glennfawcett** [comment]
So, you can "always" reproduce in the other environment?  If so, then it is likely something wrong with the specific cluster. 

Should really open up a support case and get a debug zip from the cluster to investigate.

**Comment by sjuls** [comment]
Yeah, so far it has been reproduced consistently in our environment 5 separate times.

On an upsert failure from staging table to target table cdc-sink should get stuck until it can proceed. Are you suggesting that cdc-sink is getting a successful result back from the upserts from the staging table to the target table, but that the CockroachDB cluster is somehow not applying the changes?

I'll open a support ticket with a debug zip.

**Comment by sjuls** [comment]
Hi @bobvawter ,

I _think_ I finally have a script based off [demo_up.sh](https://github.com/sjuls/cdc-sink/blob/reproduce-locally/scripts/demo_up.sh) that consistently reproduces the issue locally. Let me know what you think.

**Comment by bobvawter** [comment]
@glennfawcett PR #572 will allow us to see if we're failing to apply any specific mutation, as the applied state is now tracked in the staging database.

**Comment by RoachietheSupportRoach** [comment]
Zendesk ticket #[18927](https://cockroachdb.zendesk.com/agent/tickets/18927) has been linked to this issue.

**Comment by bobvawter** [comment]
@sjuls I have tested your script against the changes in #572 and it appears to recover from the loss of grants.  There's an additional metric, updated once per minute, that looks for dangling mutations in the staging tables: `stage_stale_mutations_count{schema="movr.public",table="user_promo_codes"} 0`

**Comment by sjuls** [comment]
Hi @bobvawter,

Looks good. I've tested against lasted main (ee3d48a3809f46bfcc1882ca175b6b8ff6ccf95d) and have been unable to provoke any data-loss. 👍
