### ISSUE TITLE
RFC: Three-way merge

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cdc-sink#509]
(Top-level issue is #487)

cdc-sink currently supports a Compare-And-Set operation (CAS) which allows cdc-sink to discard incoming mutations that do not advance a time- or version-like field. This is suitable for a limited number of active-active logical replication scenarios, but we want to allow the userscript to provide an arbitrary two- or three-way merge function.  This would allow users total control over conflict resolution.

The proposed implementation would behave as follows:
* The existing CAS behavior would need to be configured, so that the target database can generate a list of conflicting (non-applied) rows in the upsert function.
  * We will allow the user to set the comparison operation instead of assuming a strictly greater-than behavior as we do today.
* Non-applied rows are presented to a callback registered in `api.configureTable()`
* The merge callback will provide a de-conflicted row or allow the incoming mutation to be written to a dead-letter-queue (DLQ) for offline conflict resolution.

# Complications
* CDC changefeeds can be configured with the `diff` option, which would allow the `before` data to be provided to the merge function.  Other frontends may or may not provide change deltas.
* If a `dispatch` function is registered (to assign incoming mutations to various target tables), the `before` data will also need to be dispatched in order to guarantee a similar document structure in the three-way-merge case.
  * When the `before` data is passed to `dispatch`, we will need to perform per-target and per-PK lookups in the resulting document map, since it's possible for a `dispatch` function to fan-out to arbitrarily many destination tables and rows.
* The DLQ is not something that we have today, but could also be a generally-useful thing to have.  One question about the DLQ is whether or not it would be a staging-database concern or a target-database concern.
  * Since the schema of a DLQ table would be fairly trivial (i.e. basically the existing staging table design), it may be worthwhile to support placing the DLQs in the target database to better facilitate offline conflict resolution.
* The result of a successful `merge` is unconditionally applied and not subject to the CAS checks.
* If the `merge` function returns an error, this should push back on the replication loop, in the same way that an error in `dispatch` or `map` will.
* If a `map` function is also provided for the table, it will be invoked to produce the initial value that we attempt to apply to the target table (this is the current behavior). When the `merge` function provides a de-conflicted row, the `map` function __will not__ be invoked again. The `merge` function can reasonably be expected to produce applicable output.

# Userscript API

```typescript
// MergeOperation is added to the API spec. This allows us to incrementally extend
// the data available to the merge callback without needing to add an excessive
// number of arguments.
type MergeOperation = {
  before?:  Document;  // Not present in two-way case.
  existing: Document;  // Existing data that conflicted.
  meta:     Document;  // Equivalent to what you'd see in the map() function.
  proposed: Document;  // Incoming mutation.
}

// MergeResult is a union-type to apply, defer, or drop the incoming mutation.
type MergeResult = {
  apply: Document; // Unconditionally apply this document.
} | {
  dlq: string;     // Write the proposed data to the named DLQ.
} | {
  drop: boolean;   // Drop the proposed document.
}

api.configureTable("destination", {
  // cas is required in order to generate conflicts to be merged.
  // Each column name may be configured with a comparison operation.
  cas: [ "=home_region", ">updated_at" ],
  // If defined, the map function will not be called after the merge.
  map: (incoming, meta): Document => {
    // Do things
    return document
  },

  merge: (op: MergeOperation): MergeResult => {
    // Do things
    return { apply: mergedDocument };
  },
});
```

# Default merge behaviors

If we have incoming `diff` data, we can provide a default 3-way merge function that will identify the properties that change in the incoming payload. The `before` values of the changed properties will be compared to the column values currently in the target table. If the `before` values and target columns are equal, a partial update to the target row will be performed.

This default merge behavior will be available as callback within the userscript as `api.standardMerge()`.  It has the following signature:

```typescript
// standardMerge returns a merge function that performs a three-way merge
// on the target data. The optional callback allows additional refinement
// of the MergeResult (e.g. to provide CAS column values that leapfrog either
// the source or the target rows). If the merge cannot be performed (e.g. a mismatch
// in some of the delta-before values vs. target table), the operation will be
// added to the dead-letter queue.
function standardMerge(dlq: string, callback?: (op: MergeOperation, result: MergeResult) => MergeResult ) : (op: MergeOperation) => MergeResult

// If the merge can't be performed, it'll be added to the named DLQ.
api.configureTable("just_merge", {
  merge: api.standardMerge("some_dlq"),
});

// Full configuration where standardMerge() is composed with a user-provided callback.
api.configureTable("destination", {
  merge: api.standardMerge("destination_dlq", (op: MergeOperation, result: MergeResult): MergeResult => {
    if (result.dlq !=== undefined) {
      // The standard merge didn't succeed, create a fresh MergeResult.
      return { apply: customMergedDocument };
    }
    // Maybe do other things to result.apply before returning it.
    return result;
  }),
});
```

**Comment by BramGruneir** [comment]
IMO, the DLQ should be in the target.

But this makes sense to me.
