### ISSUE TITLE
Verify pglogical vs UDT in source schema

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cdc-sink#578]
May need to process TypeMessages in `pglogical/conn.go` to unpack UDTs in the input stream.

**Comment by DBAShand** [comment]
Customer is blocked on migration.  

CREATE TYPE public."WorkspaceCreationMethod" AS ENUM (
    'UNKNOWN',
    'SELF_SERVE',
    'RETOOL',
    'SELF_SERVE_ASSISTED',
    'GUEST_AUTOCREATED'
);


CREATE TABLE public."Organization" (
    id text NOT NULL,
    name text NOT NULL,
    slug text NOT NULL,
    "auth0Id" text NOT NULL,
    "createdAt" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "updatedAt" timestamp(3) without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "createdVia" public."WorkspaceCreationMethod" DEFAULT 'UNKNOWN'::public."WorkspaceCreationMethod" NOT NULL,
    "emailDomainMatchingEnabled" boolean DEFAULT false NOT NULL,
    "logoImagePathDark" text,
    "logoImagePathGlobal" text,
    "logoImagePathLight" text,
    "shouldUseThemedLogo" boolean DEFAULT true NOT NULL,
    "dateBecameMultiMember" timestamp(3) without time zone,
    "showTomeBrandingPreference" boolean DEFAULT false NOT NULL,
    "emailDomains" text[] DEFAULT ARRAY[]::text[],
    "defaultThemeId" text
);
