### ISSUE TITLE
userscripts not handling INT8 correctly

### ISSUE THREAD

**Issue by sravotto** [cockroachdb/cdc-sink#664]
When a userscript is used to process rows that contain INT8 values, the values are converted to Javascript `number` which are double precision floats. They can only represent numbers up to 2^53 - 1 (instead of  2^63-1).

To reproduce, set up a C2C environment and run the KV workload, using the following userscript:

```
import * as api from "cdc-sink@v1";
import {Document, Table} from "cdc-sink@v1";

api.configureSource("kv.public", {
    dispatch: (doc: Document, meta: Document): Record<Table, Document[]> => {
        let ret: Record<Table, Document> = {};
        ret[meta.table] = [doc];
        return ret
    }
})
```

**Comment by bobvawter** [comment]
I need to add a lint against `json.Unmarshal()` which is what's returning the float.  Instead, we should use a decoder with the `UseNumber()` option that does the right thing for large-magnitude numbers.
