### ISSUE TITLE
Demonstrate how to turn a hard delete into a soft delete

### ISSUE THREAD

**Issue by bobvawter** [cockroachdb/cdc-sink#667]
Customer request to be able to transform hard deletes from the source into soft deletes on the target. There's currently no wiring in the userscript to allow this kind of conversion from a delete operation into an upsert operation without going all the way to writing a custom apply function.

Initial thinking is to deprecate the `map()` and `deleteKey()` callbacks in favor of a more generalized `opMap: (Iterable<ApplyOp>) => Promise<Iterable<ApplyOp>>`. This would enable arbitrary transformations between kinds of operations. The move to an async function would also allow the `opMap()` to use the async SQL bindings.

Considering the soft-delete use case, we need to validate that a sparse upsert document won't nullify existing data in the target table. That is, given a upsert document of `{pk : N, deleted_at: 'timestamp'}`, existing columns remain unchanged.

**Comment by bobvawter** [comment]
Also, this is an opportunity to supply the `before` value as an optional property in the `ApplyOp` type.

**Comment by BramGruneir** [comment]
I like this change, but we should do it soon as it again changes the userscript API which we should do our best to lock down.

**Comment by bobvawter** [comment]
Solved: https://github.com/cockroachdb/cdc-sink/blob/12df027bf79b400c5049296728be54c0eb6dc4c0/internal/script/testdata/main.ts#L172-L189
